version: '3'
services:
  conpon3-web:
    container_name: conpon3-django-web
    build: .
    ports:
      - "3322:3322"
    volumes:
      - ./web:/app
      - ./log:/root/var/log
    depends_on:
      - conpon3-redis
  conpon3-redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf