version: '3'
services:
  coupon-db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: conquers666
      MYSQL_USER: conquers666
      MYSQL_PASSWORD: conquers666
      MYSQL_DATABASE: ezgo
    ports:
      - "5556:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d  # 挂载自定义配置目录，即上述的 mysql/conf/django-blog.cnf 中的配置
      - ./mysql/data:/var/lib/mysql  # 挂载数据目录
      - ./mysql/log:/var/log  # 挂载日志目录
  coupon3-web:
    container_name: conpon3-django-web
    build: .
    ports:
      - "3322:3322"
    volumes:
      - ./web:/app
      - ./log:/root/var/log
    depends_on:
      - coupon3-redis
      - coupon-db
  coupon3-redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf