# Generated by Django 3.0 on 2020-07-02 08:34

import api.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='縣市名稱', max_length=128)),
                ('picture', models.CharField(help_text='縣市圖片', max_length=128)),
                ('latitude', models.FloatField(help_text='經度', max_length=64)),
                ('longitude', models.FloatField(help_text='緯度', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='折扣名稱', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='行政區名稱', max_length=128)),
                ('latitude', models.FloatField(help_text='經度', max_length=64)),
                ('longitude', models.FloatField(help_text='緯度', max_length=64)),
                ('county', models.ForeignKey(help_text='縣市fk', on_delete=django.db.models.deletion.CASCADE, related_name='district', to='api.County')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('file', models.FileField(upload_to='', validators=[api.models.validate_file])),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(blank=True, help_text='商家名稱', max_length=128, null=True)),
                ('google_name', models.CharField(blank=True, help_text='商家名稱', max_length=128, null=True)),
                ('phone', models.CharField(blank=True, help_text='電話', max_length=64, null=True)),
                ('person', models.CharField(blank=True, help_text='聯絡人', max_length=128, null=True)),
                ('email', models.CharField(blank=True, help_text='信箱', max_length=128, null=True)),
                ('website', models.CharField(blank=True, help_text='網站', max_length=512, null=True)),
                ('address', models.CharField(help_text='商家地址', max_length=128)),
                ('latitude', models.FloatField(blank=True, help_text='經度', max_length=64, null=True)),
                ('longitude', models.FloatField(blank=True, help_text='緯度', max_length=64, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Location', null=True, srid=4326)),
                ('status', models.SmallIntegerField(default=0, help_text='商家狀態 0：待審核；1：審核通過（上架）；2：審核失敗（不顯示）')),
                ('google_status', models.SmallIntegerField(default=0, help_text='from google 0: 沒有資料 1: 有資料')),
                ('county', models.ForeignKey(help_text='縣市fk', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.County')),
                ('district', models.ForeignKey(help_text='行政區fk', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.District')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='類型名稱', max_length=128)),
                ('icon', models.CharField(help_text='標籤名稱', max_length=128)),
                ('replace_icon', models.CharField(help_text='替代標籤', max_length=128)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('picture', models.CharField(help_text='商家圖片', max_length=128)),
                ('store', models.ForeignKey(help_text='商家fk', on_delete=django.db.models.deletion.CASCADE, related_name='storeimage', to='api.Store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(blank=True, help_text='折扣標題', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='敘述', null=True)),
                ('discount_type', models.ForeignKey(help_text='折扣fk', on_delete=django.db.models.deletion.CASCADE, related_name='store_discount', to='api.DiscountType')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storediscount', to='api.Store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.ForeignKey(help_text='店家類型fk', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.StoreType'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_status', models.BooleanField(default=False, help_text='資料刪除狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(help_text='更新時間', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='刪除時間', null=True)),
                ('name', models.CharField(help_text='活動名稱', max_length=64)),
                ('description', models.TextField(blank=True, help_text='敘述', null=True)),
                ('county', models.ManyToManyField(related_name='activity', to='api.County')),
                ('store', models.ManyToManyField(related_name='activity', to='api.Store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
