# Generated by Django 3.0 on 2020-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='search_status',
            field=models.SmallIntegerField(default=1, help_text='0: 一般商店：但只有選擇活動才能被搜尋 1: 目前的一般搜尋 2: 信用卡搜尋'),
        ),
    ]
