# Generated by Django 3.0 on 2020-07-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storediscount_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(help_text='商家地址', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='county',
            field=models.ForeignKey(help_text='縣市fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.County'),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.ForeignKey(help_text='行政區fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.District'),
        ),
    ]
