# Generated by Django 3.0 on 2020-07-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200706_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, help_text='商家地址', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='county',
            field=models.ForeignKey(blank=True, help_text='縣市fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.County'),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.ForeignKey(blank=True, help_text='行政區fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='api.District'),
        ),
    ]
