# Generated by Django 3.0 on 2020-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200707_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ad',
            field=models.TextField(blank=True, default=None, help_text='廣告', null=True),
        ),
    ]
