# Generated by Django 3.0 on 2020-07-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_store_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storediscount',
            name='picture',
            field=models.CharField(default=None, help_text='商家圖片', max_length=128, null=True),
        ),
    ]
