# Generated by Django 3.0 on 2020-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200713_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storediscount',
            name='picture',
            field=models.CharField(blank=True, default=None, help_text='商家圖片', max_length=128, null=True),
        ),
    ]
