# Generated by Django 3.0 on 2020-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200714_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='picture',
            field=models.CharField(blank=True, help_text='商家圖片', max_length=128, null=True),
        ),
    ]
