# Generated by Django 3.0 on 2020-07-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200714_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pop',
            field=models.IntegerField(default=0, help_text='人氣'),
        ),
    ]
