import string
import random

letters = string.ascii_letters + string.digits + '_'
cn_name = [
    '游盈以',
    '謝佑樺',
    '邱建娥',
    '王惠嘉',
    '李承延',
    '黃子妃',
    '張家君',
    '陳姿蓉',
    '黃旺惠',
    '黃佳燕',
    '李振娥',
    '黃雯婷',
    '彭韻如',
    '黃士帆',
    '鄭佳玲',
    '崔智傑',
    '謝淑華',
    '羅華凱',
    '陳胤禎',
    '林一禾',
    '郭俊法',
    '蘇平銘',
    '林介春',
    '林慧玲',
    '紀辰聿',
    '李孟隆',
    '陳雅玲',
    '蔡文華',
    '羅庭邦',
    '劉珮啟',
    '陳禹芷',
    '王璇劭',
    '洪嘉義',
    '張雅其',
    '蘇怡君',
    '蔡明皓',
    '王建諭',
    '林威雪',
    '方世典',
    '羅昕寧',
    '何浩學',
    '姜雅琳',
    '林怡珊',
    '黃佩君',
    '王萬嬌',
    '黃順易',
    '劉蕙如',
    '李孟男',
    '劉文佩',
    '余怡菁',
    '張進琬',
    '陳宏俊',
    '李書蓁',
    '袁軒航',
    '孫若陽',
    '陳威齊',
    '黃郁年',
    '謝淑敏',
    '吳翠邦',
    '陳峻源',
    '明婷云',
    '陳林軒',
    '趙添意',
    '黃韻如',
    '王碧虹',
    '蔡桂丹',
    '鄒宗儒',
    '李仕筠',
    '姚怡樺',
    '許哲宜',
    '張家士',
    '許惠虹',
    '劉建宏',
    '陳雅竹',
    '黃淑福',
    '李峻善',
    '簡怡萍',
    '何美惠',
    '謝慧婷',
    '林國啟',
    '宋豪瑄',
    '何怡伶',
    '黃如緯',
    '陳怡潔',
    '王富添',
    '李文凱',
    '陳怡沛',
    '潘必宜',
    '李凱翔',
    '陳思齊',
    '陳婉瑜',
    '陳惠玲',
    '陳雅一',
    '王雅萍',
    '王明名',
]
en_name = [
    'Kay Davis Barker',
    'Tyler Hudson',
    'Katrina Butler Lawrence',
    'Hector Arnold',
    'Lisa E. Harper',
    'Violet Joan Parker',
    'Stacy Wanda Higgins',
    'Violet Fleming Holmes',
    'Dawn D. Aguilar',
    'Gina Chapman Porter',
    'Leah E. Miles',
    'Jenny Ana Carter',
    'Sarah Phillips Howard',
    'Jonathan Maldonado Parks',
    'Marvin Rodgers',
    'Martin Bowman',
    'Clifford Darryl Frazier',
    'Francisco Marshall Perry',
    'Alicia W. Hansen',
    'Bradley Gomez',
    'Theodore K. Coleman',
    'Travis F. Woods',
    'Jose T. Erickson',
    'Phillip P. Myers',
    'Juanita Gardner Hicks',
    'Renee Hammond',
    'Kurt M. Miles',
    'June S. Reid',
    'Heidi Morris Farmer',
    'Louise Parker',
]


def get_random_letters(count):
    return ''.join(random.choices(letters, k=count))


def get_random_number(count):
    return ''.join(random.choices(string.digits, k=count))
